In [53]:
#Syntax

In [54]:
#ML - Simple Liner Regression - Phase - 1 - Model Creation

In [55]:
import pandas as pd  #Pandas Supports Tables

In [56]:
dataset=pd.read_csv("Salary_Data.csv")

In [57]:
dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [58]:
#Input\Output Split Method

In [59]:
independent=dataset[["YearsExperience"]] #Independent - Input in the dataset
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [60]:
dependent=dataset[["Salary"]] #Dependent - Output in the dataset
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [61]:
#Training set and Test Set Split Method

In [62]:
from sklearn.model_selection import train_test_split  #Sklearn Supports Machine Learning
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [63]:
from sklearn.linear_model import LinearRegression  #These first two lines are called as a procedure
regressor=LinearRegression()
regressor.fit(X_train,y_train) #Fit - Called Function

LinearRegression()

In [64]:
weight=regressor.coef_  #How to see the calculated weight
weight

array([[9360.26128619]])

In [65]:
bais=regressor.intercept_ #How to see bais
bais

array([26777.3913412])

In [66]:
y_pred=regressor.predict(X_test) #Evaluation Metric - For Model Evaluation

In [67]:
from sklearn.metrics import r2_score  #R2 Value Identification
r_score=r2_score(y_test,y_pred)

In [69]:
r_score

0.9740993407213511

In [71]:
import pickle #How to save model
filename="finalized_model_linear.sav" #File name must be in .sav in the last

In [75]:
pickle.dump(regressor,open(filename,'wb'))

In [78]:
loaded_model=pickle.load(open("finalized_model_linear.sav",'rb')) #Checking a saved model, whether working properly 
result=loaded_model.predict([[15]])

C:\Users\bkann\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [79]:
result

array([[167181.3106341]])